Repository type-challenges-online-judge/toj-fe, pull requests merged in 2023-10, with the labels that each got.

#72 ✨[feat]: 내 제출 확인 페이지 리스트 생성
  src/components/widget/index.ts
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/components/widget/status/Status.css.ts
  src/components/widget/status/StatusBody.tsx
  src/components/widget/status/StatusBodyTr.tsx
  src/components/widget/status/StatusHeader.tsx
  src/mocks/handlers.ts
  src/pages/status/Status.css.ts
  src/pages/status/Status.tsx
  src/pages/submit/Submit.tsx
  src/type/status.ts
Labels: ✨FEAT, 🐛FIX, ⚙️CHORE

#71 ♻️ [refactor]: 메뉴바에 문제 id대신 번호 표시 , API메소드 타입 추가
  src/apis/login.ts
  src/apis/problem.ts
  src/apis/user.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/common/Navbar.tsx
  src/components/widget/main/MainProblems.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/problemdetails/ProblemDetails.tsx
  src/components/widget/probleminfo/testcases/TestCases.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/components/widget/problemsubmit/ProblemSubmit.tsx
  src/hooks/queries/problem.ts
  src/type/login.ts
  src/type/problem.ts
  src/type/user.ts
  src/util/problem.ts
Labels: ♻️REFACTOR

#76 :bug: [bug]: 기존 MSW params 참조 오류 수정
  src/mocks/handlers.ts
  src/pages/status/Status.tsx
Labels: 🐛FIX

#78 :bug: [bug]: 1- `StatusBody.tsx`의 item 길이 조건문 추가
  src/components/widget/status/StatusBody.tsx
Labels: 🐛FIX

#80 🐛 [bug]: MSW 프로덕션 환경 적용
  src/components/widget/common/Navbar.tsx
  src/components/widget/status/StatusBodyTr.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/problem/ProblemPage.tsx
Labels: 🐛FIX

#84 ✨ [feat]: 로그인 페이지 생성
  package-lock.json
  package.json
  src/apis/instance.ts
  src/apis/login.ts
  src/components/core/button/ProblemMenuButtons.tsx
  src/components/core/button/SignButton.css.ts
  src/components/core/button/SignButton.tsx
  src/components/widget/common/Navbar.tsx
  src/components/widget/index.ts
  src/components/widget/login/Login.css.ts
  src/components/widget/login/Login.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/components/widget/problemmenus/index.ts
  src/config/path.ts
  src/pages/PageRouter.tsx
  src/pages/index.ts
  src/pages/login/LoginPage.css.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/index.ts
  src/pages/problem/ProblemPage.tsx
Labels: ✨FEAT

#86 🐛 [bug]: 로그인 이후 뒤로가기 버튼에서 발생하는 에러 해결
  src/App.tsx
  src/apis/instance.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/common/Authorization.tsx
  src/components/widget/common/Navbar.tsx
  src/components/widget/index.ts
  src/components/widget/login/Login.tsx
  src/components/widget/login/LoginProcess.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/main.tsx
  src/pages/PageRouter.tsx
  src/pages/index.ts
  src/pages/loginprocess/LoginProcessPage.tsx
  src/pages/loginprocess/index.ts
Labels: ✨FEAT, 🐛FIX

#88 🔨 [chore]: URL 과 client_id 추가 및 환경에 따른 조건부 로직 추가
  src/components/widget/login/Login.tsx
  src/components/widget/login/LoginProcess.tsx
  src/config/const.ts
  vite.config.ts
Labels: ⚙️CHORE

#90 ✨ [feat]: 페이지네이션 기능 구현 및 기존 로직 수정
  src/apis/problem.ts
  src/apis/status.ts
  src/components/core/button/PaginationButtons.css.ts
  src/components/core/button/PaginationButtons.tsx
  src/components/core/button/index.ts
  src/components/widget/login/Login.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/components/widget/problemsubmit/ProblemSubmit.tsx
  src/components/widget/status/StatusBody.tsx
  src/components/widget/status/StatusBodyTr.tsx
  src/config/const.ts
  src/hooks/queries/problem.ts
  src/hooks/queries/status.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/PageRouter.tsx
  src/pages/status/Status.tsx
  src/type/status.ts
  src/type/user.ts
Labels: ✨FEAT, ⚙️CHORE

#93 ✨ [feat]: 실시간 호출 구현
  src/apis/status.ts
  src/components/core/button/PaginationButtons.tsx
  src/components/widget/status/StatusBody.tsx
  src/components/widget/status/StatusBodyTr.tsx
  src/hooks/queries/status.ts
  src/hooks/useFormatScore.ts
  src/hooks/useFormatSeconds.ts
  src/hooks/useGetByte.ts
  src/pages/status/Status.tsx
  src/type/status.ts
Labels: ✨FEAT

#99 :bug: [fix]: 새로고침시 동작하는 인증 로직에 useEffect 제거
  src/App.tsx
Labels: 🐛FIX

#100 ✨ [feat]: 페이지네이션 디자인 적용
  src/components/core/button/GoEnd.tsx
  src/components/core/button/GoLeft.tsx
  src/components/core/button/GoRight.tsx
  src/components/core/button/GoStart.tsx
  src/components/core/button/PaginationButtons.css.ts
  src/components/core/button/PaginationButtons.tsx
  src/components/widget/common/Navbar.css.ts
  src/config/const.ts
  src/pages/status/Status.tsx
  src/type/status.ts
Labels: ✨FEAT
