Repository type-challenges-online-judge/toj-fe, pull requests merged in 2023-09, with the labels that each got.

#28 [feat]: 문제 페이지 버튼 추가
  .eslintrc.json
  package-lock.json
  package.json
  public/mockData/problemList.json
  src/App.tsx
  src/components/core/button/ProblemButton.css.ts
  src/components/core/button/ProblemMenuButtons.tsx
  src/components/core/button/index.ts
  src/components/layout/CommonLayoutWithMenus.css.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/layout/index.ts
  src/components/widget/index.ts
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/example/index.ts
  src/components/widget/probleminfo/index.ts
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/template/index.ts
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/testcases/index.ts
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/probleminfo/title/index.ts
  src/components/widget/problemmenus/ProblemMenus.css.ts
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/components/widget/problemmenus/index.ts
  src/config/path.ts
  src/pages/PageRouter.tsx
  src/pages/index.ts
  src/pages/problem/ProblemPage.tsx
  src/pages/status/Status.css.ts
  src/pages/status/Status.tsx
  src/pages/status/index.ts
  src/pages/submit/Submit.tsx
  src/pages/submit/index.ts
  src/type/problem.ts
  src/util/problem.ts
Labels: ✨FEAT

#29 [feat]: 배너 생성
  src/App.css
  src/components/core/button/SignButton.css.ts
  src/components/layout/CommonLayout.css.ts
  src/components/layout/CommonLayout.tsx
  src/components/widget/index.ts
  src/components/widget/main/Banner.css.ts
  src/components/widget/main/Banner.tsx
  src/index.css
  src/main.tsx
  src/pages/PageRouter.tsx
  src/pages/main/MainPage.tsx
Labels: ✨FEAT

#30 [refactor]: submit/:problemId URL에서도 메뉴바 상태 업데이트 진행
  src/components/layout/CommonLayoutWithMenus.tsx
  src/util/problem.ts
Labels: ♻️REFACTOR

#31 [feat]: 메인 페이지 - 문제 목록 나열 및 이동
  src/components/core/button/MainProblemButton.css.ts
  src/components/core/button/MainProblemButton.tsx
  src/components/core/button/index.ts
  src/components/widget/index.ts
  src/components/widget/main/LevelLabel.css.ts
  src/components/widget/main/LevelLabel.tsx
  src/components/widget/main/MainProblems.css.ts
  src/components/widget/main/MainProblems.tsx
  src/components/widget/probleminfo/ProblemInfo.css.ts
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/data/Problems.ts
  src/data/sample.ts
  src/pages/main/MainPage.tsx
  src/type/problem.ts
  tsconfig.json
  vite.config.ts
Labels: ✨FEAT

#33 [feat]: 이미 푼 문제 표시하기
  src/components/core/button/MainProblemButton.css.ts
  src/components/core/button/MainProblemButton.tsx
  src/components/widget/main/MainProblems.tsx
  src/data/Problems.ts
  src/type/problem.ts
Labels: ✨FEAT

#34 [feat]: 문제 페이지 TS온라인에서 풀이 버튼 추가
  src/components/core/button/ProblemButton.css.ts
  src/components/core/button/ProblemMenuButtons.tsx
  src/components/core/button/TsOnlineButton.css.ts
  src/components/core/button/TsOnlineButton.tsx
  src/components/layout/CommonLayoutWithMenus.css.ts
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/problemmenus/ProblemMenus.css.ts
Labels: ✨FEAT

#35 Delete .github/workflows/ci.yml
  .github/workflows/ci.yml
Labels: ⚙️CHORE

#36 Create ci.yml
  .github/workflows/ci.yml
Labels: ⚙️CHORE

#38 [feat]: 기존코드 MSW 적용
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/get.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/common/Navbar.tsx
  src/components/widget/main/MainProblems.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/data/Problems.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/pages/problem/ProblemPage.tsx
  src/pages/status/Status.css.ts
  src/pages/status/Status.tsx
  src/type/problem.ts
  src/util/problem.ts
Labels: ✨FEAT

#42 [feat]: 문제 제출 페이지 코드 입력창 구현
  package-lock.json
  package.json
  src/components/core/button/index.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/main.tsx
  src/pages/PageRouter.tsx
  src/pages/main/MainPage.tsx
  src/pages/problem/ProblemPage.tsx
  src/pages/submit/Submit.css.ts
  src/pages/submit/Submit.tsx
Labels: ✨FEAT

#45 ✨ [feat]: 문제 메뉴바에 현재 선택한 문제 정보 추가
  src/components/core/button/ProblemButton.css.ts
  src/components/core/button/ProblemMenuButtons.tsx
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/example/index.ts
  src/components/widget/probleminfo/index.ts
  src/components/widget/probleminfo/problemdetails/ProblemDetails.tsx
  src/components/widget/probleminfo/problemdetails/index.ts
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/template/index.ts
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/testcases/index.ts
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.css.ts
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/main.tsx
  src/pages/problem/ProblemPage.tsx
  src/pages/submit/Submit.tsx
  src/util/problem.ts
Labels: ✨FEAT

#43 ♻️ [refactor]: queryFn 공통로직 분리, 전역 useQuery 적용
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/example/Example.tsx
  src/components/widget/probleminfo/template/Template.tsx
  src/components/widget/probleminfo/testcases/Testcases.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/main.tsx
  src/pages/problem/ProblemPage.tsx
  src/pages/submit/Submit.tsx
  src/util/problem.ts
Labels: ♻️REFACTOR

#49 🔨 [chore]: 프록시 서버 세팅
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/config/const.ts
  src/pages/submit/Submit.tsx
  vite.config.ts
Labels: ⚙️CHORE

#50 ♻️ [refactor]: 변경된 API useQuery 적용 및 의존된 로직 수정
  src/apis/get.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/main/MainProblems.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/components/widget/probleminfo/problemdetails/ProblemDetails.tsx
  src/components/widget/probleminfo/title/Title.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/data/Problems.ts
  src/pages/submit/Submit.tsx
  src/type/problem.ts
  src/util/problem.ts
Labels: ✨FEAT, ♻️REFACTOR

#52 ✨[feat]: 문제 제출 페이지 제출하기 버튼 구현
  src/apis/problem.ts
  src/components/core/button/BasicButton.css.ts
  src/components/core/button/BasicButton.tsx
  src/components/core/button/TsOnlineButton.tsx
  src/components/core/button/index.ts
  src/components/widget/common/Navbar.css.ts
  src/components/widget/common/Navbar.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/mocks/handlers.ts
  src/pages/submit/Submit.css.ts
  src/pages/submit/Submit.tsx
Labels: ✨FEAT

#55 ✨ [feat]: 제출 목록 데이터 생성 및 해당 타입 선언
  src/apis/problem.ts
  src/mocks/handlers.ts
  src/pages/submit/Submit.tsx
  src/type/status.ts
Labels: ✨FEAT

#56 ♻️[refactor]: 백엔드 API를 기반으로 메인페이지 로직 수정
  src/apis/problem.ts
  src/components/core/button/MainProblemButton.css.ts
  src/components/core/button/ProblemButton.css.ts
  src/components/widget/main/LevelLabel.css.ts
  src/components/widget/main/MainProblems.tsx
  src/components/widget/probleminfo/ProblemInfo.css.ts
  src/hooks/queries/problem.ts
  src/mocks/handlers.ts
  src/type/problem.ts
Labels: ♻️REFACTOR

#57 ♻️ [refactor]: 기존 문제 세부정보 API , useQuery로직 리팩토링
  src/apis/get.ts
  src/apis/problem.ts
  src/components/layout/CommonLayoutWithMenus.tsx
  src/components/widget/probleminfo/ProblemInfo.tsx
  src/hooks/queries/problem.ts
  src/pages/submit/Submit.tsx
Labels: ♻️REFACTOR

#59 :sparkles: [feat]: 로그인 구현 및 accessToken 기반 API 호출 확인
  .gitignore
  package-lock.json
  package.json
  src/apis/login.ts
  src/apis/user.ts
  src/components/widget/common/Navbar.tsx
  src/config/const.ts
  src/main.tsx
  vite.config.ts
Labels: ✨FEAT

#61 :sparkles: [feat]: 쿼리스트링 기반 문제 반환 MSW 메소드 추가
  src/components/widget/common/Navbar.tsx
  src/components/widget/problemmenus/ProblemMenus.tsx
  src/mocks/handlers.ts
  src/pages/status/Status.tsx
  src/pages/submit/Submit.tsx
Labels: ✨FEAT

#68 ✨ [feat]: accessToken 로그아웃 방지 및 자동 로그아웃 구현
  src/App.tsx
  src/apis/instance.ts
  src/apis/login.ts
  src/components/widget/common/Navbar.tsx
  src/stores/type.ts
  src/stores/useAuthStore.ts
  src/stores/useSampleStore.ts
  src/stores/useUserInfoStore.ts
Labels: ✨FEAT
